/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_h2_command_dml_gpu_GMath */

#ifndef _Included_org_h2_command_dml_gpu_GMath
#define _Included_org_h2_command_dml_gpu_GMath
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_h2_command_dml_gpu_GMath
 * Method:    cudaSum
 * Signature: ([FI)F
 */
JNIEXPORT jfloat JNICALL Java_org_h2_command_dml_gpu_GMath_cudaSum
  (JNIEnv *, jclass, jfloatArray, jint);

/*
 * Class:     org_h2_command_dml_gpu_GMath
 * Method:    cudaMax
 * Signature: ([FI)F
 */
JNIEXPORT jfloat JNICALL Java_org_h2_command_dml_gpu_GMath_cudaMax
  (JNIEnv *, jclass, jfloatArray, jint);

#ifdef __cplusplus
}
#endif
#endif
