/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_h2_command_dml_gpu_GMath */

#ifndef _Included_org_h2_command_dml_gpu_GMath
#define _Included_org_h2_command_dml_gpu_GMath
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_h2_command_dml_gpu_GMath
 * Method:    cudaSum
 * Signature: ([FI)F
 */
JNIEXPORT jfloat JNICALL Java_org_h2_command_dml_gpu_GMath_cudaSum
  (JNIEnv *, jclass, jfloatArray, jint);

/*
 * Class:     org_h2_command_dml_gpu_GMath
 * Method:    cudaMemAlloc
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_org_h2_command_dml_gpu_GMath_cudaMemAlloc
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_h2_command_dml_gpu_GMath
 * Method:    cudaMemFree
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_h2_command_dml_gpu_GMath_cudaMemFree
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
